In [1]:
# Regra de Cramer. A = 3x3
# Matriz quadrática
# Determinante != 0
"""
    O padrão de arquivo txt deve ser somente com números e espacos, sendo pertencentes
    a B os elementos da última coluna da direita para a esquerda:
    A = Matriz
    B = Termos Independentes
    [A 3x3][B 3x1]:
        a11 a12 a13 b11
        a21 a22 a23 b21
        a31 a32 a33 b31

    """
from math import sqrt

import numpy as np
from numpy import linalg, matrix


def matrix_file(file):
    a = []
    b = []

    with open(file, "r", encoding="utf-8") as f:

        for line in f:
            values = [float(x) for x in line.split()]
            if values:
                a.append(values[0:-1])
                b.append(values[-1])

    return [a, b]


def is_square(n):
    if n < 0:
        return False
    root = sqrt(n)
    return root.is_integer()


def determinant_sarrus(matrix):
    sarrus = []
    for line in matrix:
        new_line = line + line[0:2]
        sarrus.append(new_line)

    positive = sum(sarrus[0][i] * sarrus[1][i + 1] * sarrus[2][i + 2] for i in range(3))
    negative = sum(sarrus[0][i + 2] * sarrus[1][i + 1] * sarrus[2][i] for i in range(3))

    det = positive - negative

    return


def det_np(matrix_a):  # usada em aula
    return linalg.det(matrix_a)


def cramer(matrix, terms, column_index):  # detAi / detA
    new_matrix = [line[:] for line in matrix]

    for i in range(len(new_matrix)):
        new_matrix[i][column_index] = terms[i]

    return new_matrix


def main():
    path = "aula_03_matriz.txt"  # considerando que o txt esteja no mesmo diretorio do script
    A, b = matrix_file(path)

    lines = len(A)
    cols = len(A[0]) if A else 0
    elements = is_square(16)
    det = determinant_sarrus(A)

    print(f"Matriz A: {A}")
    print(f"Termos independentes B: {b}")
    print(f"Determinante de A: {det}")

    if elements == True and det != 0:
        A1 = cramer(A, b, 0)
        detA1 = determinant_sarrus(A1)

        A2 = cramer(A, b, 1)
        detA2 = determinant_sarrus(A2)

        A3 = cramer(A, b, 2)
        detA3 = determinant_sarrus(A3)

        print(f"Solucao do sistema por Cramer: {(detA1/det), (detA2/det), (detA3/det)}")

    else:
        print("A regra de Cramer não pode ser usada")


main()

Matriz A: [[2.0, 1.0, 1.0], [0.3, 2.0, 0.25], [1.0, 1.0, 2.0]]
Termos independentes B: [39.0, 13.0, 45.0]
Determinante de A: 5.450000000000001
Solucao do sistema por Cramer: (9.999999999999998, 2.9999999999999996, 15.999999999999995)


In [31]:
# Eliminacao de Gauss
import numpy as np
from numpy import linalg, matrix


def matrix_file(file):
    a = []
    b = []

    with open(file, "r", encoding="utf-8") as f:

        for line in f:
            values = [float(x) for x in line.split()]
            if values:
                a.append(values[0:-1])
                b.append(values[-1])

    return np.array(a, dtype=float), np.array(b, dtype=float)


def gauss(A, b):

    n = len(b)

    # Eliminação
    for k in range(n - 1):

        for i in range(k + 1, n):

            m = A[i][k] / A[k][k]

            A[i][k:] = A[i][k:] - m * A[k][k:]
            b[i] = b[i] - m * b[k]

    # Substituição regressiva
    x = np.zeros(n)

    for i in range(n - 1, -1, -1):

        soma = np.dot(A[i][i + 1 :], x[i + 1 :])

        x[i] = (b[i] - soma) / A[i][i]

    return x


def main():

    path = "aula_03_matriz.txt"

    A, b = matrix_file(path)

    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)

    x = gauss(A, b)

    print("Solução:", x)


main()

Solução: [10.  3. 16.]


In [27]:
# Eliminacao de Gauss-Jordan
import numpy as np
from numpy import linalg, matrix

"""
A * X = B

[2 1 1] [t] = [39]
[0.3 2 0.25] [x] = [13]
[1 1 2] [n] = [45]

A * X = B -> I X = S
(A ** -1 * A) * X = A ** -1 * B
S = A ** -1 * B
"""


def matrix_file(file):
    a = []
    b = []

    with open(file, "r", encoding="utf-8") as f:

        for line in f:
            values = [float(x) for x in line.split()]
            if values:
                a.append(values[0:-1])
                b.append(values[-1])

    return np.array(a), np.array(b)


def matriz_inversa(matriz):
    return linalg.inv(matriz)


def matriz_solucao(A_inversa, matriz_b):
    return np.matmul(A_inversa, matriz_b)


def main():
    path = "aula_03_matriz.txt"  # considerando que o txt esteja no mesmo diretorio do script
    A, b = matrix_file(path)
    print(A)
    print(b)

    A_inversa = matriz_inversa(A)
    print(A_inversa)

    solucao_matriz = matriz_solucao(A_inversa, b)
    print("Gauss-Jordan: ", solucao_matriz)


main()

[[2.   1.   1.  ]
 [0.3  2.   0.25]
 [1.   1.   2.  ]]
[39. 13. 45.]
[[ 0.68807339 -0.18348624 -0.32110092]
 [-0.06422018  0.55045872 -0.03669725]
 [-0.31192661 -0.18348624  0.67889908]]
Gauss-Jordan:  [10.  3. 16.]


In [26]:
# Gauss-Seidel

import numpy as np
from numpy import linalg, matrix

"""
x0 = [0, 0, 0]

A * X = B

[2 1 1] [t] = [39]
[0.3 2 0.25] [x] = [13]
[1 1 2] [n] = [45]

A * X = B -> I X = S
(A ** -1 * A) * X = A ** -1 * B
S = A ** -1 * B
"""


def matrix_file(file):
    a = []
    b = []

    with open(file, "r", encoding="utf-8") as f:

        for line in f:
            values = [float(x) for x in line.split()]
            if values:
                a.append(values[0:-1])
                b.append(values[-1])

    return np.array(a), np.array(b)


def conditions(matriz):  # limitada a matriz 3x3
    # |x1| >= |x2| + |x3|
    x1 = abs(matriz[0][0]) >= abs(matriz[0][1]) + abs(matriz[0][2])
    x2 = abs(matriz[1][1]) >= abs(matriz[1][0]) + abs(matriz[1][2])
    x3 = abs(matriz[2][2]) >= abs(matriz[2][0]) + abs(matriz[2][1])

    return x1, x2, x3


def gauss_seidel(A, b):

    t = 0
    x = 0
    n = 0

    precisao = 0.01
    erro_t = erro_x = erro_n = 1

    k = 0

    while erro_t > precisao or erro_x > precisao or erro_n > precisao:

        k += 1

        t1 = (b[0] - x - n) / 2
        x1 = (b[1] - 0.3 * t1 - 0.25 * n) / 2
        n1 = (b[2] - t1 - x1) / 2

        erro_t = abs((t1 - t) / t1)
        erro_x = abs((x1 - x) / x1)
        erro_n = abs((n1 - n) / n1)

        t, x, n = t1, x1, n1

    return t, x, n, k


def main():
    path = "aula_03_matriz.txt"  # considerando que o txt esteja no mesmo diretorio do script
    A, b = matrix_file(path)
    print(A)
    print(b)

    t, x, n = conditions(A)
    print(t, x, n)

    gs = gauss_seidel(A, b)
    print("Gauss-Seidel:", gs)


main()

[[2.   1.   1.  ]
 [0.3  2.   0.25]
 [1.   1.   2.  ]]
[39. 13. 45.]
True True True
Gauss-Seidel: (10.019766406250003, 3.0045553515625, 15.98783912109375, 5)


In [41]:
# Metodo de Newton para sistemas nao lineares
# Jacobiana automatica com SymPy

import numpy as np
import sympy as sp


def read_equations(file):

    eqs = []

    with open(file, "r", encoding="utf-8") as f:

        for line in f:
            line = line.strip()

            if line:
                eqs.append(sp.sympify(line))

    return eqs


def build_system(eqs):

    vars = sorted(list(eqs[0].free_symbols), key=lambda x: x.name)

    F = sp.Matrix(eqs)

    J = F.jacobian(vars)

    f_num = sp.lambdify([vars], F, "numpy")
    j_num = sp.lambdify([vars], J, "numpy")

    return vars, f_num, j_num


def newton(f, j, x0, tol=0.001, max_iter=50):

    x = np.array(x0, dtype=float)

    for k in range(max_iter):

        F_val = np.array(f(x), dtype=float).flatten()

        J_val = np.array(j(x), dtype=float)

        try:
            delta = np.linalg.solve(J_val, F_val)
        except np.linalg.LinAlgError:
            print("\nJacobiana singular. Tente outro chute inicial.")
            return x, k

        x_new = x - delta

        erro = np.linalg.norm(x_new - x)

        print(f"Iteração {k+1}: {x_new}  erro = {erro}")

        x = x_new

        if erro < tol:
            return x, k + 1

    return x, max_iter


def main():

    path = "equacoes.txt"

    eqs = read_equations(path)
    print(eqs)

    vars, f, j = build_system(eqs)

    print("\nVariáveis:", vars)

    print("\nDigite o chute inicial:")

    x0 = []
    for v in vars:
        val = float(input(f"{v}0 = "))
        x0.append(val)

    sol, it = newton(f, j, x0)

    print("\nSolução aproximada:")
    for v, s in zip(vars, sol):
        print(f"{v} = {s}")

    print("Iterações:", it)


main()

[x + y - 5, x**2 + y**2 - 13]

Variáveis: [x, y]

Digite o chute inicial:


x0 =  0
y0 =  1


Iteração 1: [-2.  7.]  erro = 6.324555320336759
Iteração 2: [0.22222222 4.77777778]  erro = 3.1426968052735442
Iteração 3: [1.30623306 3.69376694]  erro = 1.5330228318407537
Iteração 4: [1.79840597 3.20159403]  erro = 0.6960376081002291
Iteração 5: [1.97103727 3.02896273]  erro = 0.2441375244618394
Iteração 6: [1.99920709 3.00079291]  erro = 0.03983813597640069
Iteração 7: [1.99999937 3.00000063]  erro = 0.001120456122816473
Iteração 8: [2. 3.]  erro = 8.877162415543459e-07

Solução aproximada:
x = 1.9999999999996076
y = 3.000000000000393
Iterações: 8
