In [39]:
import numpy as np
from numpy import linalg, matrix

# print(' para função y = a0 + a1 * x + a2 * x**2

x0 = 0
y0 = 0

x1 = 5
y1 = 2.846954

x2 = 10
y2 = 1.795416

eixo_x = [0, 5, 10]
eixo_y = [0, 2.846954, 1.795416]

m = len(eixo_x)

soma1 = x0 + x1 + x2
soma2 = (x0 * x0) + (x1 * x1) + (x2 * x2)
soma3 = (x0 * x0 * x0) + (x1 * x1 * x1) + (x2 * x2 * x2)
soma4 = (x0 * x0 * x0 * x0) + (x1 * x1 * x1 * x1) + (x2 * x2 * x2 * x2)

soma5 = y0 + y1 + y2
soma6 = (x0 * y0) + (x1 * y1) + (x2 * y2)
soma7 = ((x0 * x0) * y0) + ((x1 * x1) * y1) + ((x2 * x2) * y2)

# matriz
print('A X = B')
matriz_A = np.array([[m, soma1, soma2], [soma1, soma2, soma3], [soma2, soma3, soma4]])
matriz_B = np.array([soma5, soma6, soma7])

print('matriz A')
print(matriz_A)
print('matriz B')
print(matriz_B)


def detx(matriz):
    return linalg.det(matriz)


print('Determinante de A')
det = detx(matriz_A)


print(det)

A X = B
matriz A
[[    3    15   125]
 [   15   125  1125]
 [  125  1125 10625]]
matriz B
[  4.64237  32.18893 250.71545]
Determinante de A
62500.00000000017
